# Generated by Django 3.0.7 on 2020-07-12 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_master_id', models.CharField(max_length=30)),
                ('last_message_id', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'group_chat',
            },
        ),
        migrations.CreateModel(
            name='GroupChatMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=30)),
                ('message_type', models.CharField(max_length=30)),
                ('old_file_name', models.CharField(blank=True, max_length=30, null=True)),
                ('send_time', models.CharField(max_length=30)),
                ('send_user_id', models.CharField(max_length=30)),
                ('received_group_id', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'group_chat_message',
            },
        ),
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=30)),
                ('message_type', models.CharField(max_length=30)),
                ('old_file_name', models.CharField(blank=True, max_length=30, null=True)),
                ('send_time', models.CharField(max_length=30)),
                ('send_user_id', models.CharField(max_length=30)),
                ('read_user_id', models.CharField(max_length=30)),
                ('boolread', models.IntegerField()),
            ],
            options={
                'db_table': 'private_chat',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('port', models.IntegerField(blank=True, default=22, null=True)),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=50)),
                ('icon', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserUser',
            fields=[
                ('main_user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('vice_user_id', models.CharField(max_length=30)),
                ('type', models.IntegerField()),
                ('remark', models.CharField(blank=True, max_length=30, null=True)),
                ('tag', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'user_user',
                'unique_together': {('main_user_id', 'vice_user_id')},
            },
        ),
        migrations.CreateModel(
            name='Lable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_lable', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkdb.UserUser')),
            ],
            options={
                'db_table': 'lable',
            },
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('group_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
                ('ulvgmid', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'group_user',
                'unique_together': {('group_id', 'user_id')},
            },
        ),
    ]
