# Generated by Django 3.0.8 on 2020-07-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_auto_20200705_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('port', models.IntegerField(default=22)),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
