# Generated by Django 3.0.8 on 2020-07-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='port',
            field=models.IntegerField(blank=True, default=22, null=True),
        ),
    ]
