# Generated by Django 3.0.8 on 2020-07-06 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0004_auto_20200706_0023'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useruser',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Lable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_lable', models.CharField(max_length=30)),
                ('main_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.UserUser')),
            ],
            options={
                'db_table': 'lable',
            },
        ),
        migrations.RemoveField(
            model_name='useruser',
            name='grouping',
        ),
    ]
