# Generated by Django 3.0.8 on 2020-07-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0007_auto_20200706_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruser',
            name='main_user_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
